apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: epd0or8lm-nodejs 
  janus-idp.io/tekton: epd0or8lm-nodejs
  backstage.io/kubernetes-id: epd0or8lm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: epd0or8lm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  